loja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from loja.settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('', include('produto.urls')),
    path('admin/', admin.site.urls),
    path('perfil/', include('perfis.urls')),
    path('pedido/', include('pedido.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

produto/urls.py
from django.urls import path
from .import views

app_name = 'produto'

urlpatterns = [
    path('', views.ListaProduto.as_view(), name='lista'),
    path('<slug>', views.DetalheProduto.as_view(), name='detalhe'),
    path('adicionaraocarrinho/',
         views.AdicionarAoCarrinho.as_view(), name='adicionar'),
    path('removerdocarrinho/', views.RemoverDoCarrinho.as_view(), name='remover'),
    path('carrinho/', views.Carrinho.as_view(), name='carrinho'),
    path('resumodacompra/', views.ResumodaCompra.as_view(), name='resumo'),
]

produto/models.py
from PIL import Image
from django.db import models
from django.db.models.fields import CharField
import os
from django.conf import settings
from django.utils.text import slugify
from utils import utils


class Produto(models.Model):
    nome = models.CharField(max_length=255, verbose_name='nome_produto')
    descricao_curta = models.TextField(
        max_length=255, verbose_name='Descrição')
    descricao_longa = models.TextField(verbose_name='desc_longa_produto')
    imagem = models.ImageField(upload_to='produto_imagens/%Y/%m')
    slug = models.SlugField(unique=True, blank=True, null=True)
    preco_marketing = models.FloatField(verbose_name='Preço')
    preco_marketing_promocional = models.FloatField(
        default=0, verbose_name='Preço Promo', null=True, blank=True)
    tipo = models.CharField(
        default='V',
        max_length=1,
        choices=(
            ('V', 'Variável'),
            ('S', 'Simples'),
        )
    )

    def get_preco_formatado(self):
        return utils.formatatexto(self.preco_marketing)
    get_preco_formatado.short_description = 'Preço'

    def get_preco_promo_formatado(self):
        if self.preco_marketing_promocional:
            return utils.formatatexto(self.preco_marketing_promocional)
        return ''
    get_preco_promo_formatado.short_description = 'Preço Promocional'

    @staticmethod
    def resize_image(img, new_width):
        img_full_path = os.path.join(settings.MEDIA_ROOT, img.name)
        img_pil = Image.open(img_full_path)
        original_width, original_heigth = img_pil.size

        if not original_width <= new_width:
            img_pil.close()
            return

        new_height = round((original_heigth * new_width) / original_width)

        new_img = img_pil.resize((new_width, new_height), Image.LANCZOS)

        new_img.save(
            img_full_path,
            quality=50,
            optimize=True

        )
        print('a imagem foi redimensionada')

    def save(self, *args, **kwargs):
        if not self.slug:
            slug = f'{slugify(self.nome)}'
            self.slug = slug

        super().save(*args, **kwargs)

        max_image_size = 800

        if self.imagem:
            self.resize_image(self.imagem, max_image_size)

    def __str__(self):
        return self.nome


class Variacao(models.Model):
    nome = models.CharField(max_length=50)
    produto = models.ForeignKey(Produto, on_delete=models.CASCADE)
    preco = models.FloatField()
    preco_promocional = models.FloatField(default=0)
    estoque = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.nome

    class Meta:
        verbose_name = 'Variação'
        verbose_name_plural = 'Varições'

produto/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views import View
from django.http import HttpResponse
from . import models
from django.contrib import messages
from pprint import pprint


class ListaProduto(ListView):
    model = models.Produto
    template_name = 'produto/lista.html'
    context_object_name = 'produtos'
    paginate_by = 9


class DetalheProduto(DetailView):
    model = models.Produto
    template_name = 'produto/detalhe.html'
    context_object_name = 'produto'
    slug_url_kwarg = 'slug'


class AdicionarAoCarrinho(View):
    def get(self, *args, **kwargs):
        # TODO: remover este if
        # if self.request.session.get('carrinho'):
        #     del self.request.session['carrinho']
        #     self.request.session.save()
        referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')
        quantidade_solicitada = int(self.request.GET.get('quantidade'))
        if not variacao_id:
            messages.error(
                self.request,
                'Produto não existe'
            )
            return redirect(referer)

        variacao = get_object_or_404(models.Variacao, id=variacao_id)
        variacao_estoque = variacao.estoque
        produto = variacao.produto

        produto_id = produto.id
        produto_nome = produto.nome
        variacao_nome = variacao.nome or ''
        preco_unitario = variacao.preco
        preco_unitario_promocional = variacao.preco_promocional
        quantidade = quantidade_solicitada
        slug = produto.slug
        imagem = produto.imagem.name

        if variacao.estoque < 1:
            messages.error(
                self.request,
                'Estoque insuficiente'
            )
            return redirect(referer)

        if not self.request.session.get('carrinho'):
            self.request.session['carrinho'] = {}
            self.request.session.save()

        carrinho = self.request.session['carrinho']

        if variacao_id in carrinho:
            quantidade_carrinho = carrinho[variacao_id]['quantidade']
            quantidade_carrinho += quantidade_solicitada

            if variacao_estoque < quantidade_carrinho:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_carrinho}X'
                    f'no produto produto "{produto_nome}"'
                    f'. Adicionamos {variacao_estoque}X no seu carrinho'
                )
                quantidade_carrinho = variacao_estoque

            carrinho[variacao_id]['quantidade'] = quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo'] = preco_unitario * \
                quantidade_carrinho
            carrinho[variacao_id]['preco_quantitativo_promocional'] = \
                preco_unitario_promocional * quantidade_carrinho

        else:
            # TODO: variação não existe no carrinho.
            if variacao_estoque < quantidade_solicitada:
                messages.warning(
                    self.request,
                    f'Estoque insuficiente para {quantidade_solicitada} '
                    f'no produto "{produto_nome}"'
                    f'. Adicionamos {variacao_estoque} X no seu carrinho'
                )
                quantidade_solicitada = variacao_estoque

            carrinho[variacao_id] = {
                'produto_id': produto_id,
                'produto_nome': produto_nome,
                'variacao_nome': variacao_nome,
                'variacao_id': variacao_id,
                'preco_unitario': preco_unitario,
                'preco_unitario_promocional': preco_unitario_promocional,
                'preco_quantitativo': preco_unitario * quantidade_solicitada,
                'preco_quantitativo_promocional': preco_unitario_promocional * quantidade_solicitada,
                'quantidade': quantidade_solicitada,
                'slug': slug,
                'imagem': imagem
            }

        self.request.session.save()
        messages.success(
            self.request,
            f'Produto {produto_nome} {variacao_nome} adicionado ao seu carrinho'
            f' {quantidade_solicitada} X'
        )
        return redirect(referer)


class RemoverDoCarrinho(View):
    def get(self, *args, **kwargs):
        referer = self.request.META.get(
            'HTTP_REFERER',
            reverse('produto:lista')
        )
        variacao_id = self.request.GET.get('vid')
        if not variacao_id:
            return redirect(referer)
        if not self.request.session.get('carrinho'):
            return redirect(referer)
        if variacao_id not in self.request.session['carrinho']:
            return redirect(referer)

        carrinho = self.request.session['carrinho']

        messages.success(
            self.request,
            f'Produto >> {carrinho[variacao_id]["produto_nome"]} {carrinho[variacao_id]["variacao_nome"]} <<'
            f' removido do seu carrinho'
        )
        del self.request.session['carrinho'][variacao_id]
        self.request.session.save()
        return redirect(referer)


class Carrinho(View):
    def get(self, *args, **kwargs):
        contexto = {
            'carrinho': self.request.session.get('carrinho')
        }
        return render(self.request, 'produto/carrinho.html', contexto)


class ResumodaCompra(View):
    def get(*args, **kwargs):
        return HttpResponse('Finalizar')

produto/templates/produto/carrinho.html
{% extends 'base.html' %}

{% load omfilters %}

{% load static %}

{% block conteudo %}

{% if carrinho %}
<div class="row mt-3">
    <div class="col">
        <h3>Carrinho de compras</h3>
        <p class="lead">Os produtos, quantidades e preços que você escolheu.</p>

        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th class="d-none d-lg-block">Imagem</th>
                    <th>Produto</th>
                    <th>V.</th>
                    <th>QTD.</th>
                    <th>Total</th>
                </tr>

                {% for linha in carrinho.values %}
                    <tr>
                        <td class="d-none d-lg-block">
                            <img class="cart-img" src="{% get_media_prefix %}{{ linha.imagem }}">
                        </td>
                        <td>
                            <a href="{% url 'produto:detalhe' linha.slug %}">
                                {{ linha.produto_nome|title }}
                            </a>
                            <a class="ml-3" href="{% url 'produto:remover' %}?vid={{ linha.variacao_id }}">
                                <i class="fas fa-times-circle text-danger" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>{{ linha.variacao_nome }}</td>
                        <td>
                            {{ linha.quantidade }} x
                            {% if linha.preco_quantitativo_promocional %}
                                {{ linha.preco_unitario_promocional|formata_preco }}
                            {% else %}
                                {{ linha.preco_unitario|formata_preco }}
                            {% endif %}
                        </td>
                        <td>
                            {% if linha.preco_quantitativo_promocional %}
                                {{ linha.preco_quantitativo_promocional|formata_preco }}
                            {% else %}
                                {{ linha.preco_quantitativo|formata_preco }}
                            {% endif %}
                        </td>
                    </tr>
                    {% endfor %}

            </table>
        </div>
    </div>
</div>



<div class="row mt-3">
    <div class="col-lg">
        <p class='lead'>Total no carrinho</p>

        <div class='table-responsive'>
            <table class="table">
                <tr>
                    <td class="font-weight-bold">Total</td>
                    <td>{{ carrinho|cart_totals|formata_preco }}</td>
                </tr>
            </table>
        </div>
    </div>
    <div class="col-lg mt-auto">
        <a class="btn btn-lg btn-block btn-primary" href="#">
            Finalizar a compra
        </a>
    </div>
</div>

{% else %}

    <div class="row mt-3">
        <div class="col">
            <h3>Carrinho Vazio</h3>
            <p class="lead">Não há produtos no seu carrinho.</p>
        </div>
    </div>

{% endif %}
{% endblock %}

produto/templates/produto/detalhe.html
{% extends 'base.html' %}
{% load omfilters %}

{% block conteudo %}


<div class="row">
    <div class="col-lg-12">
        <div class="row">
            <div class="col-lg">
                <div class="row no-gutters">
                    <div class="col-lg-12">
                        <img class="img-fluid" src="{{ produto.imagem.url }}">
                    </div>
                </div>
            </div>
            <div class="col-lg">
                <div class="mt-4 mt-lg-0">
                    <h1 class="h2">{{ produto.nome|title }}</h1>
                    <p class="lead">{{ produto.descricao_curta|linebreaks }}</p>
                    <p class="lead">
                        {% if produto.preco_marketing_promocional %}
                            <span id="variation-preco-promocional" class="lead product-price">
                                {{ produto.preco_marketing_promocional|formata_preco }}
                            </span>

                            <span id="variation-preco"
                            class="lead product-old-price text-muted">
                                {{ produto.preco_marketing|formata_preco }}
                            </span>
                        {% else %}
                            <span id="variation-preco-promocional" class="lead product-price">
                                {{ produto.preco_marketing|formata_preco }}
                            </span>
                            <span id="variation-preco"
                            class="lead product-old-price text-muted">
                            </span>
                        {% endif %}
                    </p>

                    <form action="{% url 'produto:adicionar' %}" id="form-add-to-cart">
                        
                            <div class="form-group">
                                <select id="select-variacoes" name="vid" class="form-control form-control-lg">
                                    {% for variacao in produto.variacao_set.all %}
                                        
                                    {% if variacao.preco_promocional %}
                                        <option data-preco="{{ variacao.preco|formata_preco }}" 
                                        data-preco-promocional="{{ variacao.preco_promocional|formata_preco }}" 
                                        value="{{ variacao.id }}">
                                        {{ variacao|title }}
                                        </option>
                                    {% else %}
                                        <option 
                                        data-preco-promocional="{{ variacao.preco|formata_preco }}" 
                                        value="{{ variacao.id }}">
                                        {{ variacao|title }}
                                        </option>
                                    {% endif %}

                                    {% endfor %}
                                </select>
                            </div>
                            #TODO: modificar para input type number com value dinamico vindo de ajax
                            <div class="form-group">
                                <div class="col-md-3">
                                    <label class="control-label col-sm-1" for="quantidade">Quantidade:</label>
                                    <select id="select-variacoes" name="quantidade" class="form-control form-control-lg">
                                        <option value="1">1</option>
                                        <option value="2">2</option>
                                        <option value="3">3</option>
                                        <option value="4">4</option>
                                        <option value="5">5</option>
                                        <option value="6">6</option>
                                        <option value="7">7</option>
                                        <option value="8">8</option>
                                    </select>
                                </div>
                            </div>
                        <div class="text-left">
                            <button type="submit" class="btn btn-primary btn-lg btn-block">
                                <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                                Adicionar ao carrinho
                            </button>
                        </div>

                    </form>


                </div>
            </div>
        </div>


        <div class="row">
            <div class="col-lg-12">
                <div class="mt-5 mb-5">
                    <h2 class="text-center">{{ produto.nome|title }}</h2>
                    <p>{{ produto.descricao_longa|linebreaks }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

produto/templates/produto/lista.html
{% extends 'base.html' %}
{% block conteudo %}
{% load omfilters %}

  
      <div class="row">
        <div class="col-lg-12">
          <div class="card-columns">


            {% for produto in produtos %}
            <a href="{{ produto.slug }}">
            <div class="card">
              <img
                class="card-img-top"
                src="{{ produto.imagem.url }}"
                alt="{{ produto.nome }}"
              />
            </a>
              <div class="card-body">
                <h5 class="card-title">{{ produto.nome|title }}</h5>
                <p class="card-text">
                  {{ produto.descricao_curta }}
                </p>
                <div class="container product-price-block text-center">

                {% if produto.preco_marketing_promocional %}

                  <span class="product-price"> {{ produto.preco_marketing_promocional|formata_preco }} </span>
                  <span class="product-old-price text-muted"> {{ produto.preco_marketing|formata_preco }} </span>
                
                {% else %}
                    <span class="product-price"> {{ produto.preco_marketing|formata_preco }} </span>
                {% endif %}

                </div>
              </div>
              <div
                class="
                  card-footer
                  bg-transparent
                  border-top-light-custom
                  text-center
                "
              >
                <a
                  href="{{ produto.slug }}"
                  class="btn btn-primary btn-sm m-1 btn-block"
                >
                  <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                  Comprar
                </a>
              </div>
            </div>
            {% endfor %}



          </div>
        </div>
      </div>
      <div class="row mt-3">
        <div class="col">
          {% include 'parciais/_pagination.html' %}
        </div>
      </div>



{% endblock %}